Refactor
Jerzy9/Cars pull request #8
Opened 2021-04-25 21:45 UTC by falken01

pls accept

2021-04-26 09:16 UTC, Jerzy9 requested changes

2021-04-26 09:16 UTC, konradzb commented on Cars/DTOs/StaffDTO/CreateEmployeeDto.cs
> +    public record CreateEmployeeDto
This DTO should  be named EmployeeInputDto, because all other objects are named like this

2021-04-26 09:16 UTC, konradzb commented on Cars/DTOs/StaffDTO/CreateEmployeeDto.cs
> +namespace Cars.StaffDTO
For DTOs we use Cars.Dtos namespace

2021-04-26 09:16 UTC, konradzb commented on Cars/DTOs/StaffDTO/EmployeeDto.cs
> +namespace Cars.StaffDTO
Same namepsace problem

2021-04-26 09:16 UTC, konradzb commented on Cars/DTOs/StaffDTO/UpdateEmployeeDto.cs
> +    public record UpdateEmployeeDto
This record should be named EmployeeEditDto to match the pattern

2021-04-26 09:16 UTC, Jerzy9 commented on Cars/Model/Employee.cs
> +        public static int lastId = 0;
lastId cannot be here, when we will be connecting to the mySQL DB, migration will create wrong Table, with lastId in it

2021-04-26 09:16 UTC, Jerzy9 commented on Cars/Repositories/Employee/FakeEmployeeRepository.cs
> +    public class FakeEmployeeRepository : IEmployeeRepository
We named our repositories according to the pattern "Fake<model_name>Dao" and the interface "I<model_name>Dao"

2021-04-26 09:16 UTC, Jerzy9 commented on Cars/Service/Employee/IStaffService.cs
> +    interface IStaffService
IEmployeeService*

2021-04-26 09:16 UTC, Jerzy9 commented on Cars/Service/Employee/IStaffService.cs
> +    {
There should be methods, witch will be implemented in the implementationof this interface, I mean EmployeeService. Do same thing here according to the pattern we did.

2021-04-26 09:16 UTC, Jerzy9 commented on Cars/Controllers/EmployeeRestController.cs
> +        private readonly IEmployeeRepository repository;
Controller doen't have repository at all. It just has a service. After calling method in service, the service calls method in Repo. Look how it works in for example Car Object.

2021-04-26 09:16 UTC, Jerzy9 commented on Cars/Controllers/EmployeeRestController.cs
> +                return NoContent();
Instead of NoContent(), return the boolean value like we discussed

2021-05-09 19:23 UTC, minikowsky commented
Getting some errors. IEmployeeService should contain method CreateEmployee that returns EmployeeDto, not ActionResult<EmployeeDto>. In IEmpoloyeeDao you have method editEmployeeByID wich is void but it should return Employee object - error in EmployeeService. Also, you don't have contstructors in EmplyeeDtos, I think they are required.

2021-05-09 20:22 UTC, merged